#!/usr/bin/env node
const tls = require('tls');

if(process.argv.length<4) {
  console.log("Syntax error: "+process.argv[1]+" <server> [port]");
  process.exit(-1);
}
let insecure=true;
if(process.argv.length==5) insecure=false;

console.log("Trying "+process.argv[2]+"...");
let sock = tls.connect(process.argv[3],process.argv[2],{rejectUnauthorized:insecure});
sock.setEncoding('utf8');
sock.on('connect',(d) => {
  console.log("Connected to "+process.argv[2]+".");

  process.stdin.pipe(sock);
  process.stdin.resume();
});
sock.on('data',(d) => { process.stdout.write(d); });
sock.on('end', () => {
  console.log('Connection closed.');
  process.exit(1);
});
